language: node_js
node_js:
  - 4.2
services:
  - elasticsearch
  - redis-server
before_script:
  - sleep 10
  - curl -XPOST 'localhost:9200/_bulk?pretty' --data-binary "@./test/fixtures/fixture.json"
after_script:
    - curl -XDELETE 'localhost:9200/fixture'
